INSERT INTO route  (name, bus_id) VALUES ('Stad. Municipal - Roman', 1);
INSERT INTO route  (name, bus_id) VALUES ('Roman - Stad. Municipal', 1);
INSERT INTO route  (name, bus_id) VALUES ('Stadionul Municipal - Magurele', 2);
INSERT INTO route  (name, bus_id) VALUES ('Magurele - Stadionul Municipal', 2);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Rasaritul - Fabrica de var', 3);
INSERT INTO route  (name, bus_id) VALUES ('Fabrica de var - Rasaritul - Livada Postei', 3);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Noua', 4);
INSERT INTO route  (name, bus_id) VALUES ('Noua - Livada Postei', 4);
INSERT INTO route  (name, bus_id) VALUES ('Gara Brasov - Timisul de jos', 5);
INSERT INTO route  (name, bus_id) VALUES ('Timisul de jos - Gara Brasov', 5);
INSERT INTO route  (name, bus_id) VALUES ('Bariera Bartolomeu - Fundaturii (*IAR Ghimbav)', 6);
INSERT INTO route  (name, bus_id) VALUES ('Fundaturii (*IAR Ghimbav) - Bariera Bartolomeu - ', 6);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Poiana Brasov', 7);
INSERT INTO route  (name, bus_id) VALUES ('Poiana Brasov - Livada Postei', 7);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Belvedere', 8);
INSERT INTO route  (name, bus_id) VALUES ('Belvedere - Livada Postei', 8);
INSERT INTO route  (name, bus_id) VALUES ('Triaj - Noua', 9);
INSERT INTO route  (name, bus_id) VALUES ('Noua - Triaj', 9);
INSERT INTO route  (name, bus_id) VALUES ('Saturn - Depozite ILF - Stadionul Municipal', 10);
INSERT INTO route  (name, bus_id) VALUES ('Stadionul Municipal - Depozite ILF - Saturn', 10);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - ICPC - Baciului (*Stupinii Noi)', 11);
INSERT INTO route  (name, bus_id) VALUES ('Baciului (*Stupinii Noi) - ICPC - Livada Postei', 11);
INSERT INTO route  (name, bus_id) VALUES ('Avantgarden - Roman', 12);
INSERT INTO route  (name, bus_id) VALUES ('Roman - Avantgarden', 12);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Lânii - Fundaturii (*IAR Ghimbav, **ICPC)', 13);
INSERT INTO route  (name, bus_id) VALUES ('Fundaturii (*IAR Ghimbav, **ICPC) - Lânii - Livada Postei', 13);
INSERT INTO route  (name, bus_id) VALUES ('IZVOR - Livada Postei', 14);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - IZVOR', 14);
INSERT INTO route  (name, bus_id) VALUES ('Gara Brasov - Noua', 15);
INSERT INTO route  (name, bus_id) VALUES ('Noua - Gara Brasov', 15);
INSERT INTO route  (name, bus_id) VALUES ('Craiter - Hidro A', 16);
INSERT INTO route  (name, bus_id) VALUES ('Hidro A - Craiter', 16);
INSERT INTO route  (name, bus_id) VALUES ('Gara Brasov - Lujerului', 17);
INSERT INTO route  (name, bus_id) VALUES ('Lujerului - Gara Brasov', 17);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Stupini Lujerului', 18);
INSERT INTO route  (name, bus_id) VALUES ('Stupini Lujerului - Livada Postei', 18);
INSERT INTO route  (name, bus_id) VALUES ('Pe Tocile - Roman (*Panselelor)', 19);
INSERT INTO route  (name, bus_id) VALUES ('Roman (*Panselelor) - Pe Tocile', 19);
INSERT INTO route  (name, bus_id) VALUES ('Triaj - Harmanului - Hidro A', 20);
INSERT INTO route  (name, bus_id) VALUES ('Hidro A - Harmanului - Triaj', 20);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Rulmentul', 21);
INSERT INTO route  (name, bus_id) VALUES ('Rulmentul - Livada Postei', 21);
INSERT INTO route  (name, bus_id) VALUES ('Pe Tocile - Gara Brasov', 22);
INSERT INTO route  (name, bus_id) VALUES ('Gara Brasov - Pe Tocile', 22);
INSERT INTO route  (name, bus_id) VALUES ('Rulmentul (*Coresi) - Stadionul Muncipal', 23);
INSERT INTO route  (name, bus_id) VALUES ('Stadionul Muncipal - Rulmentul (*Coresi)', 23);
INSERT INTO route  (name, bus_id) VALUES ('Avantgarden - Independentei - Triaj', 24);
INSERT INTO route  (name, bus_id) VALUES ('Triaj - Independentei - Avantgarden', 24);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Grivitei - Caramidariei', 25);
INSERT INTO route  (name, bus_id) VALUES ('Caramidariei - Grivitei - Livada Postei', 25);
INSERT INTO route  (name, bus_id) VALUES ('Saturn - Stadionul Tineretului', 26);
INSERT INTO route  (name, bus_id) VALUES ('Stadionul Tineretului - Saturn', 26);
INSERT INTO route  (name, bus_id) VALUES ('Triaj - A.Vlaicu - Stadionul Municipal', 27);
INSERT INTO route  (name, bus_id) VALUES ('Stadionul Municipal - A.Vlaicu - Triaj', 27);
INSERT INTO route  (name, bus_id) VALUES ('(Parc Ind. Ghimbav) Fundaturii - Gara Brasov', 28);
INSERT INTO route  (name, bus_id) VALUES ('Gara Brasov - (Parc Ind. Ghimbav) Fundaturii', 28);
INSERT INTO route  (name, bus_id) VALUES ('Valea Cetatii - Gara Brasov - Coresi', 29);
INSERT INTO route  (name, bus_id) VALUES ('Coresi - Gara Brasov - Valea Cetatii', 29);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Timis-Triaj', 30);
INSERT INTO route  (name, bus_id) VALUES ('Timis-Triaj - Livada Postei', 30);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Independentei', 31);
INSERT INTO route  (name, bus_id) VALUES ('Independentei - Livada Postei', 31);
INSERT INTO route  (name, bus_id) VALUES ('Solomon - Camera de Comert', 32);
INSERT INTO route  (name, bus_id) VALUES ('Camera de Comert - Solomon', 32);
INSERT INTO route  (name, bus_id) VALUES ('Facultatea de Constructii - Panselelor', 33);
INSERT INTO route  (name, bus_id) VALUES ('Panselelor - Facultatea de Constructii', 33);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Harmanului - Triaj', 34);
INSERT INTO route  (name, bus_id) VALUES ('Triaj - Harmanului - Livada Postei', 34);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Rulmentul', 35);
INSERT INTO route  (name, bus_id) VALUES ('Rulmentul - Livada Postei', 35);
INSERT INTO route  (name, bus_id) VALUES ('Stadionul Tineretului - Valea Cetatii', 36);
INSERT INTO route  (name, bus_id) VALUES ('Valea Cetatii - Stadionul Tineretului', 36);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Saturn', 37);
INSERT INTO route  (name, bus_id) VALUES ('Saturn - Livada Postei', 37);
INSERT INTO route  (name, bus_id) VALUES ('Rulmentul - Roman', 38);
INSERT INTO route  (name, bus_id) VALUES ('Roman - Rulmentul', 38);
INSERT INTO route  (name, bus_id) VALUES ('Rulmentul - Saturn', 39);
INSERT INTO route  (name, bus_id) VALUES ('Saturn - Rulmentul', 39);
INSERT INTO route  (name, bus_id) VALUES ('Valea Cetatii - Triaj', 40);
INSERT INTO route  (name, bus_id) VALUES ('Triaj - Valea Cetatii', 40);
INSERT INTO route  (name, bus_id) VALUES ('Valea Cetatii - Livada Postei', 41);
INSERT INTO route  (name, bus_id) VALUES ('Livada Postei - Valea Cetatii', 41);
INSERT INTO route  (name, bus_id) VALUES ('Valea Cetatii - Roman', 42);
INSERT INTO route  (name, bus_id) VALUES ('Roman - Valea Cetatii', 42);